add_newline = true 

# format = "$directory$git_branch$git_status$python$golang$terraform$kubernetes$character"

[directory]
truncate_to_repo = true

[git_branch]
symbol = "git:"

[python]
symbol = "py:"

[golang]
symbol = "go:"

[terraform]
symbol = "tf:"

[kubernetes]
disabled = false

[aws]
disabled = true

[gcloud]
disabled = true

[cmd_duration]
min_time = 3_000
format = "took [$duration]($style) "

[status]
disabled = false
format = '[✖ $status]($style) '

